spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true


  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret: dev-only-secret-key-with-32-chars-minimum
    previous-secrets:


logging:
  level:
    com.fiap.midasfintech: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springdoc: INFO
    org.springframework.security: INFO
